services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    env_file:
      - headscale.env
    environment:
      - HEADSCALE_NOISE_PRIVATE_KEY # Wird später automatisch gesetzt
    # WICHTIG: Keine ports: Sektion! Coolify kümmert sich um das Routing.
    volumes:
      - ./data:/data
      - ./config:/etc/headscale
    cap_add:
      - NET_BIND_SERVICE