services:
  headscale:
    image: 'headscale/headscale:latest'
    container_name: headscale-v8ggo0kg8w0o84gg8wko4gkc
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - '-c /config/config.yaml'
    volumes:
      - '/data/coolify/applications/v8ggo0kg8w0o84gg8wko4gkc/data:/data'
      - '/data/coolify/applications/v8ggo0kg8w0o84gg8wko4gkc/config.yaml:/config.yaml:ro'
    cap_add:
      - NET_BIND_SERVICE
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.463
      - coolify.applicationId=20
      - coolify.type=application
      - coolify.name=headscale-v8ggo0kg8w0o84gg8wko4gkc
      - coolify.resourceName=headscale-controller
      - coolify.projectName=jellyfin
      - coolify.serviceName=headscale-controller
      - coolify.environmentName=production
      - coolify.pullRequestId=0
    networks:
      v8ggo0kg8w0o84gg8wko4gkc: null
    environment:
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: v8ggo0kg8w0o84gg8wko4gkc
      COOLIFY_CONTAINER_NAME: headscale-v8ggo0kg8w0o84gg8wko4gkc
      SERVICE_NAME_HEADSCALE: headscale
    env_file:
      - .env
networks:
  v8ggo0kg8w0o84gg8wko4gkc:
    name: v8ggo0kg8w0o84gg8wko4gkc
    external: true